# Generated by Django 5.0 on 2025-10-23 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("total_conversations", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("avg_messages_per_conversation", models.FloatField(default=0.0)),
                ("avg_conversation_duration", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Analytics",
                "verbose_name_plural": "Chat Analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="IntentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent_name", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("usage_count", models.IntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("successful_responses", models.IntegerField(default=0)),
                ("failed_responses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Intent Analytics",
                "verbose_name_plural": "Intent Analytics",
                "ordering": ["-date", "-usage_count"],
                "unique_together": {("intent_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("message_sent", "Message Sent"),
                            ("conversation_started", "Conversation Started"),
                            ("conversation_ended", "Conversation Ended"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
